import type { Metadata } from 'next'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions governing your use of the Pristine Data AI platform.',
  alternates: { canonical: 'https://pristinedata.ai/terms' },
}

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: [
      'By accessing or using the Pristine Data AI platform and services (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you are using the Service on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms.',
      'If you do not agree to these Terms, do not access or use the Service.',
    ],
  },
  {
    title: '2. Description of Service',
    body: [
      'Pristine Data AI provides a B2B sales intelligence platform that includes contact and company prospecting, data enrichment, buying signal detection, AI-generated campaign content, outreach sequencing, and deal intelligence tools (collectively, the "Service").',
      'We reserve the right to modify, suspend, or discontinue any part of the Service at any time with reasonable notice. We will not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.',
    ],
  },
  {
    title: '3. Account Registration',
    body: [
      'To access the Service, you must create an account and provide accurate, complete, and current information. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.',
      'You must notify us immediately at support@pristinedata.ai if you become aware of any unauthorised use of your account. We are not liable for any loss resulting from unauthorised access to your account that occurs before notification.',
      'You may not share your account credentials, create accounts on behalf of others without their consent, or use the Service to impersonate any person or entity.',
    ],
  },
  {
    title: '4. Acceptable Use',
    body: [
      'You agree to use the Service only for lawful B2B sales and marketing purposes and in compliance with all applicable laws and regulations, including anti-spam laws (CAN-SPAM, CASL, GDPR), data protection regulations, and email marketing regulations in your jurisdiction.',
      'You must not use the Service to: send unsolicited bulk email in violation of applicable law; target individuals for personal (non-business) outreach; harvest or scrape data for purposes other than legitimate sales prospecting; attempt to circumvent usage limits or access controls; reverse engineer or extract data from the platform for resale or redistribution; or use the Service in any way that could damage, disable, or impair our systems.',
      'We reserve the right to suspend or terminate accounts that we determine, in our sole discretion, are being used in violation of these Terms or applicable law.',
    ],
  },
  {
    title: '5. Data and Enrichment',
    body: [
      'The contact and company data provided through the Service is sourced from third-party enrichment providers and aggregated for B2B prospecting purposes. You acknowledge that data accuracy is not guaranteed and may vary by contact, geography, and time.',
      'You are responsible for ensuring your use of enrichment data complies with applicable data protection laws. Where required by law (e.g., GDPR), you are responsible for establishing a lawful basis for processing contact data you obtain through the Service.',
      'Contact data exported from the platform may be used for legitimate B2B outreach but may not be resold, sublicensed, or used to build competing data products.',
    ],
  },
  {
    title: '6. Intellectual Property',
    body: [
      'The Service, including all software, algorithms, AI models, content, and user interface elements, is owned by Pristine Inc. and protected by intellectual property laws. These Terms do not grant you any rights to our intellectual property except the limited licence to use the Service as described herein.',
      'You retain ownership of any data you import into the Service, including CRM data, contact lists, and campaign content you create. By using the Service, you grant us a limited licence to process and display your data solely to provide the Service to you.',
      'Opportunity Playbooks, enrichment results, and other outputs generated by the Service are provided for your use in connection with the Service. You may not redistribute or resell these outputs.',
    ],
  },
  {
    title: '7. Payment and Billing',
    body: [
      'Access to the Service requires a paid subscription. By subscribing, you authorise us to charge your payment method on the schedule specified at the time of purchase (monthly or annually).',
      'All fees are exclusive of applicable taxes. You are responsible for any taxes associated with your use of the Service.',
      'Subscriptions renew automatically unless cancelled before the renewal date. Credits included in your plan do not roll over between billing periods unless expressly stated in your plan terms.',
      'We reserve the right to change pricing with 30 days written notice. Your continued use of the Service after the effective date of a price change constitutes acceptance of the new pricing.',
    ],
  },
  {
    title: '8. Refunds and Cancellation',
    body: [
      'You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period. We do not provide refunds for unused portions of a subscription period except where required by applicable law.',
      'If you believe you have been charged in error, contact billing@pristinedata.ai within 30 days of the charge. We will review and respond within 10 business days.',
    ],
  },
  {
    title: '9. Disclaimer of Warranties',
    body: [
      'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.',
      'We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components, or that data provided through the Service will be accurate, complete, or current.',
    ],
  },
  {
    title: '10. Limitation of Liability',
    body: [
      'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PRISTINE INC. AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE.',
      'OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.',
    ],
  },
  {
    title: '11. Indemnification',
    body: [
      'You agree to indemnify, defend, and hold harmless Pristine Inc. and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to your use of the Service, your violation of these Terms, or your violation of any applicable law or third-party rights.',
    ],
  },
  {
    title: '12. Termination',
    body: [
      'We may suspend or terminate your access to the Service immediately, without prior notice, if you breach these Terms, fail to pay fees when due, or if we are required to do so by law.',
      'Upon termination, your right to use the Service ceases immediately. We will retain your data for 30 days following termination, after which it will be permanently deleted. You may request an export of your data before termination takes effect.',
    ],
  },
  {
    title: '13. Governing Law',
    body: [
      'These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in Delaware.',
    ],
  },
  {
    title: '14. Changes to Terms',
    body: [
      'We may update these Terms from time to time. We will provide at least 14 days notice of material changes via email or prominent notice on our platform. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms.',
      'If you do not agree to the revised Terms, you must stop using the Service before the effective date of the changes.',
    ],
  },
  {
    title: '15. Contact',
    body: [
      'For questions about these Terms, contact us at legal@pristinedata.ai or by mail at: Pristine Inc., United States.',
    ],
  },
]

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-16">
        <div className="max-w-2xl mx-auto px-6 py-20">
          <div className="mb-12">
            <p className="text-xs font-semibold uppercase tracking-widest text-indigo-500 mb-4">Legal</p>
            <h1 className="text-4xl font-bold text-slate-900 dark:text-white mb-4">Terms of Service</h1>
            <p className="text-slate-500 dark:text-slate-400 text-sm">Last updated: April 24, 2026</p>
          </div>

          <p className="text-base text-slate-600 dark:text-slate-400 leading-relaxed mb-12">
            These Terms of Service govern your access to and use of the Pristine Data AI platform. Please read them carefully before using the Service. By accessing or using our platform, you agree to be bound by these Terms.
          </p>

          <div className="space-y-10">
            {sections.map(({ title, body }) => (
              <section key={title} className="border-t border-slate-100 dark:border-slate-800 pt-8">
                <h2 className="text-base font-semibold text-slate-900 dark:text-white mb-4">{title}</h2>
                <div className="space-y-3">
                  {body.map((p, i) => (
                    <p key={i} className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{p}</p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
